# Generated by Django 5.1 on 2025-05-25 05:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_incrrect'),
        ('question', '0002_alter_question_choice_1_alter_question_choice_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incrrect',
            new_name='Incorrect',
        ),
    ]
