# Generated by Django 5.1 on 2025-05-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_rename_incrrect_incorrect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incorrect',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='incorrect',
            old_name='user_id',
            new_name='user',
        ),
    ]
