# Generated by Django 5.1 on 2025-05-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_rename_question_id_incorrect_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='user_id',
            new_name='user',
        ),
    ]
